#+TITLE:     README
#+AUTHOR:    Austin F. Frank
#+EMAIL:     austin.frank@gmail.com
#+DATE:      {{{modification-time(%Y-%m-%d)}}}
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+STARTUP:   indent

This package implements several variations of the visual world
paradigm commonly used in psycholinguistics and other fields of
cognitive science.


* COPYING
Copyright 2011, Austin F. Frank <aufrank@haskins.yale.edu>

This file is part of VisualWorld.

VisualWorld is free software: you can redistribute it and/or modify it
under the terms of the Lesser GNU General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

VisualWorld is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the Lesser
GNU General Public License for more details.

You should have received a copy of the Lesser GNU General Public
License along with VisualWorld.  If not, see
[[http://www.gnu.org/licenses/]].

* Setup
** TODO Dependencies
*** Python 2.6
*** Portaudio (for recording sounds)
*** pylink
** Installation of VisualWorld
*** Unix-like operating systems (Mac OS X, GNU/Linux)
Start by downloading the dependencies listed above.  Install each of
those, and then run
#+BEGIN_SRC sh :exports src
python setup.by build
sudo python setup.py install
#+END_SRC

or, if available,
#+BEGIN_SRC sh :exports src
sudo pip install .
#+END_SRC
*** TODO Windows operating systems

* TODO Running

* TODO Development

* TODO Reporting errors

* TODO FAQ
* TODO Credits
